### PR TITLE
Format key in the same way as certificate

### PR DESCRIPTION
**Pull request by samwmarsh**
## Description

Currently only the certificate has a prefix and suffix added if it doesn’t exist. This is to bring the SAML key inline.

## Motivation and Context

In https://github.com/SpecterOps/BloodHound/issues/83 we’ve been having issues with SAML working when not using AAD as the identity provider. We’ve been able to get this working with values within the config.json, however we’re currently getting issues when passing in environment variables. We’re concerned that the \n in the key is causing it to be interpreted incorrectly when being passed as an env var in Helm/K8s so we’d like to add this to attempt to resolve this issue.

## How Has This Been Tested?

Currently tested same logic already works for certificate. I’m unaware of the impacts, I’m new to golang and it’s quite confusing to attempt to follow so please test on my behalf!

## Types of changes

-   [ ] Chore (a change that does not modify the application functionality)
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [ ] Documentation updates are needed, and have been made accordingly.
-   [ ] I have added and/or updated tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] My changes include a database migration.

### CODE REVIEW

**Comment by samwmarsh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by samwmarsh** [comment]
recheck

**Comment by codydbentley** [comment]
Hi @samwmarsh. To help provide context to these changes, would you mind please editing the PR to describe the changes made and include links to an issue if it is related? Thank you for the contribution!

**Comment by samwmarsh** [comment]
@codydbentley updated! Let me know if you need anything else

**Comment by samwmarsh** [comment]
@codydbentley we've done some testing this morning and seen the following (which makes me sad and this PR invalid, but also raises a bug)

**Test Case 1**
Using the code in this PR for tls.go, 
supply the SAML certificate without the BEGIN/END certificate values via the config.json file
supply the SAML key without the BEGIN/END private key values via the config.json file
error message "[panic recovery] runtime error: invalid memory address or nil pointer dereference"

**Test Case 2**
Using the code in the main branch for tls.go
supply the SAML certificate without BEGIN/END certificate values via the config.json file
supply the SAML key **with** the BEGIN/END private key values via the config.json file
SAML works

**Test Case 3**
Using the code in the main branch for tls.go
supply the SAML certificate without BEGIN/END certificate values via environment variable bhe_saml_sp_cert
supply the SAML key **with** the BEGIN/END private key values via environment variable bhe_saml_sp_key
error message "[panic recovery] runtime error: invalid memory address or nil pointer dereference"

Test cases 2 and 3 were where we were before raising this PR, with the idea that the \n character in the BEGIN PRIVATE KEY and END PRIVATE KEY lines were causing this error, however as proven with test case 1, this is not the case. In fact, the kernel panic happens in both cases 1 and 3.

**Comment by StephenHinck** [comment]
@samwmarsh - we have some work upcoming in this area that will allow us to review and get this across the line properly. Our apologies for the delay in merging!

**Comment by urangel** [comment]
@samwmarsh Apologies for the slow review and thank you for your patience. I noticed there are new suggestions mentioned in https://github.com/SpecterOps/BloodHound/issues/83, have you tried them out by chance? Specifically, this comment: https://github.com/SpecterOps/BloodHound/issues/83#issuecomment-2221120052. 

The code changes in this pull request are well contained and clear though it looks like the newly added `formattedKey` variable is not being used anywhere so the formatting changes have no effect in the logic.

Let us know if you try the suggestions mentioned here https://github.com/SpecterOps/BloodHound/issues/83#issuecomment-2221120052 and if it works or not for you. Thank you!

**Comment by samwmarsh** [comment]
Hi @urangel,
I think we ended up injecting these as k8s secrets into the json file directly in the end. I'm not sure what state it is in now, just that the previous test steps in https://github.com/SpecterOps/BloodHound/pull/175#issuecomment-1786994484 were the state at the time.

Thanks,
Sam

**Review by byt3n33dl3 — CHANGES_REQUESTED** [review]
Just want to see the runway -->

**Comment by StephenHinck** [comment]
We have addressed the lack of documentation in this area in https://github.com/SpecterOps/BloodHound/wiki/Configuring-SSO. If there's additional missing information, we would be happy to expand - please let me know!

Regardless, @samwmarsh , I would be happy to send you a SWAG package for your contribution and patience with our team in looking at these changes. If you would be interested, please send me an email at shinck [AT] specterops [DOT] io with your address and t-shirt size, and I would be happy to get that in the mail to you :-)

**Pull request closed without merging**
