### PR TITLE
BP-881: Update README.md to reflect the docker-compose.yml filename change, which breaks the hyperlink

### PR DESCRIPTION
**Pull request by Roltere**
Changed the link for 'examples/docker-compose/docker-compose.yaml'.  The file is now called 'examples/docker-compose/docker-compose.yml'

The original link results in a 404 as the file did not exist, due to the extension change

## Description

*Describe your changes in detail*

## Motivation and Context

This PR addresses: BP-881

## How Has This Been Tested?

Documentation update, no testing needed

## Types of changes

- Chore (a change that does not modify the application functionality)
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- Database Migrations

## Checklist:

- [x] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [x] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [x] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

### CODE REVIEW

**Comment by Roltere** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Roltere** [comment]
recheck

**Review by StephenHinck — APPROVED** [review]
Good catch, thank you!

**Comment by StephenHinck** [comment]
Tracked internally as BP-881.

**Comment by StephenHinck** [comment]
@Roltere - thank you very much for your contribution.

If you wouldn't mind reaching out to me at shinck [at] specterops [dot] io with your address and t-shirt size, I'd love to get you a swag package as a token of our appreciation for your contribution!

**Review by zinic — APPROVED** [review]
Thanks!

**Review by juggernot325 — APPROVED** [review]
Thank you for fixing this up!

**Pull request merged**
