### PR TITLE
BED-4622: Enforce `goimports`

### PR DESCRIPTION
**Pull request by superlinkx**
## Description

- Fixes all formatting issues that diverge from normal `goimports`
- Adds a new step to `prepare-for-codereview` to ensure `goimports` has run

## Motivation and Context

This PR addresses: BED-4622

*Why is this change required? What problem does it solve?*

We've long used `goimports` as our source of truth for formatting preference, but there are some minor differences in how that tooling is used in different IDEs. This is the first step towards ensuring that code is actually formatted by the canonical `goimports`. There will be evaluation of this for our pipelines in the future.

## How Has This Been Tested?

Ran through the new commands and ensured the new dependency is picked up properly

## Types of changes

- Chore (a change that does not modify the application functionality)

## Checklist:

- [x] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [x] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [x] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

### CODE REVIEW

**Review by urangel — APPROVED** [review]
Aw yiss

**Comment by juggernot325** [comment]
For some reason the `just deps` command is not installing `goimports` for me.

```
➜  bhce git:(BED-4622) ✗ just stbernard deps
{"level":"info","time":"2024-07-25T13:49:21.272486-04:00","message":"Running go install for /Users/jbarnett/dev/bloodhound-enterprise/bhce"}
{"level":"info","time":"2024-07-25T13:49:22.149043-04:00","message":"Finished go install for /Users/jbarnett/dev/bloodhound-enterprise/bhce"}
{"level":"info","time":"2024-07-25T13:49:22.14916-04:00","message":"Running go install for /Users/jbarnett/dev/bloodhound-enterprise/bhce"}
{"level":"info","time":"2024-07-25T13:49:22.767212-04:00","message":"Finished go install for /Users/jbarnett/dev/bloodhound-enterprise/bhce"}
{"level":"info","time":"2024-07-25T13:49:22.767375-04:00","message":"Running yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/cmd/ui"}
➤ YN0000: ┌ Resolution step
➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui doesn't provide @testing-library/dom (pa1bac), requested by @testing-library/user-event
➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui [b226e] doesn't provide @testing-library/dom (p2a54b), requested by @testing-library/user-event
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @mui/system (pec2ad), requested by @mui/x-date-pickers
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/is (p33505), requested by redux-saga-test-plan
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/symbols (p0b773), requested by redux-saga-test-plan
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @testing-library/dom (p99d58), requested by @testing-library/user-event
➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides luxon (p5ac9e) with version 2.5.2, which doesn't satisfy what @date-io/luxon requests
➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides react (p74846) with version 18.2.0, which doesn't satisfy what @mui/styles requests
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide redux (p6f2da), requested by redux-devtools-extension
➤ YN0002: │ sigma@npm:2.4.0 doesn't provide graphology-types (pe610a), requested by graphology-utils
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 258ms
➤ YN0000: Done with warnings in 0s 653ms
{"level":"info","time":"2024-07-25T13:49:23.833247-04:00","message":"Finished yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/cmd/ui"}
{"level":"info","time":"2024-07-25T13:49:23.833442-04:00","message":"Running yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/packages/javascript/bh-shared-ui"}
➤ YN0000: ┌ Resolution step
➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui doesn't provide @testing-library/dom (pa1bac), requested by @testing-library/user-event
➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui [b226e] doesn't provide @testing-library/dom (p2a54b), requested by @testing-library/user-event
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @mui/system (pec2ad), requested by @mui/x-date-pickers
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/is (p33505), requested by redux-saga-test-plan
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/symbols (p0b773), requested by redux-saga-test-plan
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @testing-library/dom (p99d58), requested by @testing-library/user-event
➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides luxon (p5ac9e) with version 2.5.2, which doesn't satisfy what @date-io/luxon requests
➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides react (p74846) with version 18.2.0, which doesn't satisfy what @mui/styles requests
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide redux (p6f2da), requested by redux-devtools-extension
➤ YN0002: │ sigma@npm:2.4.0 doesn't provide graphology-types (pe610a), requested by graphology-utils
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 262ms
➤ YN0000: Done with warnings in 0s 661ms
{"level":"info","time":"2024-07-25T13:49:24.946727-04:00","message":"Finished yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/packages/javascript/bh-shared-ui"}
{"level":"info","time":"2024-07-25T13:49:24.946867-04:00","message":"Running yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/packages/javascript/js-client-library"}
➤ YN0000: ┌ Resolution step
➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui doesn't provide @testing-library/dom (pa1bac), requested by @testing-library/user-event
➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui [b226e] doesn't provide @testing-library/dom (p2a54b), requested by @testing-library/user-event
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @mui/system (pec2ad), requested by @mui/x-date-pickers
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/is (p33505), requested by redux-saga-test-plan
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/symbols (p0b773), requested by redux-saga-test-plan
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @testing-library/dom (p99d58), requested by @testing-library/user-event
➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides luxon (p5ac9e) with version 2.5.2, which doesn't satisfy what @date-io/luxon requests
➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides react (p74846) with version 18.2.0, which doesn't satisfy what @mui/styles requests
➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide redux (p6f2da), requested by redux-devtools-extension
➤ YN0002: │ sigma@npm:2.4.0 doesn't provide graphology-types (pe610a), requested by graphology-utils
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 258ms
➤ YN0000: Done with warnings in 0s 650ms
{"level":"info","time":"2024-07-25T13:49:26.016716-04:00","message":"Finished yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/packages/javascript/js-client-library"}
{"level":"info","time":"2024-07-25T13:49:26.01673-04:00","message":"Command `deps` completed successfully"}
➜  bhce git:(BED-4622) ✗ just goimports
Running goimports, check for file drift
find: goimports: No such file or directory
```

**Comment by superlinkx** [comment]
> For some reason the `just deps` command is not installing `goimports` for me.
> 
> ```
> ➜  bhce git:(BED-4622) ✗ just stbernard deps
> {"level":"info","time":"2024-07-25T13:49:21.272486-04:00","message":"Running go install for /Users/jbarnett/dev/bloodhound-enterprise/bhce"}
> {"level":"info","time":"2024-07-25T13:49:22.149043-04:00","message":"Finished go install for /Users/jbarnett/dev/bloodhound-enterprise/bhce"}
> {"level":"info","time":"2024-07-25T13:49:22.14916-04:00","message":"Running go install for /Users/jbarnett/dev/bloodhound-enterprise/bhce"}
> {"level":"info","time":"2024-07-25T13:49:22.767212-04:00","message":"Finished go install for /Users/jbarnett/dev/bloodhound-enterprise/bhce"}
> {"level":"info","time":"2024-07-25T13:49:22.767375-04:00","message":"Running yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/cmd/ui"}
> ➤ YN0000: ┌ Resolution step
> ➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui doesn't provide @testing-library/dom (pa1bac), requested by @testing-library/user-event
> ➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui [b226e] doesn't provide @testing-library/dom (p2a54b), requested by @testing-library/user-event
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @mui/system (pec2ad), requested by @mui/x-date-pickers
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/is (p33505), requested by redux-saga-test-plan
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/symbols (p0b773), requested by redux-saga-test-plan
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @testing-library/dom (p99d58), requested by @testing-library/user-event
> ➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides luxon (p5ac9e) with version 2.5.2, which doesn't satisfy what @date-io/luxon requests
> ➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides react (p74846) with version 18.2.0, which doesn't satisfy what @mui/styles requests
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide redux (p6f2da), requested by redux-devtools-extension
> ➤ YN0002: │ sigma@npm:2.4.0 doesn't provide graphology-types (pe610a), requested by graphology-utils
> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Fetch step
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Link step
> ➤ YN0000: └ Completed in 0s 258ms
> ➤ YN0000: Done with warnings in 0s 653ms
> {"level":"info","time":"2024-07-25T13:49:23.833247-04:00","message":"Finished yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/cmd/ui"}
> {"level":"info","time":"2024-07-25T13:49:23.833442-04:00","message":"Running yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/packages/javascript/bh-shared-ui"}
> ➤ YN0000: ┌ Resolution step
> ➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui doesn't provide @testing-library/dom (pa1bac), requested by @testing-library/user-event
> ➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui [b226e] doesn't provide @testing-library/dom (p2a54b), requested by @testing-library/user-event
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @mui/system (pec2ad), requested by @mui/x-date-pickers
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/is (p33505), requested by redux-saga-test-plan
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/symbols (p0b773), requested by redux-saga-test-plan
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @testing-library/dom (p99d58), requested by @testing-library/user-event
> ➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides luxon (p5ac9e) with version 2.5.2, which doesn't satisfy what @date-io/luxon requests
> ➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides react (p74846) with version 18.2.0, which doesn't satisfy what @mui/styles requests
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide redux (p6f2da), requested by redux-devtools-extension
> ➤ YN0002: │ sigma@npm:2.4.0 doesn't provide graphology-types (pe610a), requested by graphology-utils
> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Fetch step
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Link step
> ➤ YN0000: └ Completed in 0s 262ms
> ➤ YN0000: Done with warnings in 0s 661ms
> {"level":"info","time":"2024-07-25T13:49:24.946727-04:00","message":"Finished yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/packages/javascript/bh-shared-ui"}
> {"level":"info","time":"2024-07-25T13:49:24.946867-04:00","message":"Running yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/packages/javascript/js-client-library"}
> ➤ YN0000: ┌ Resolution step
> ➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui doesn't provide @testing-library/dom (pa1bac), requested by @testing-library/user-event
> ➤ YN0002: │ bh-shared-ui@workspace:packages/javascript/bh-shared-ui [b226e] doesn't provide @testing-library/dom (p2a54b), requested by @testing-library/user-event
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @mui/system (pec2ad), requested by @mui/x-date-pickers
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/is (p33505), requested by redux-saga-test-plan
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @redux-saga/symbols (p0b773), requested by redux-saga-test-plan
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide @testing-library/dom (p99d58), requested by @testing-library/user-event
> ➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides luxon (p5ac9e) with version 2.5.2, which doesn't satisfy what @date-io/luxon requests
> ➤ YN0060: │ bloodhound-ui@workspace:cmd/ui provides react (p74846) with version 18.2.0, which doesn't satisfy what @mui/styles requests
> ➤ YN0002: │ bloodhound-ui@workspace:cmd/ui doesn't provide redux (p6f2da), requested by redux-devtools-extension
> ➤ YN0002: │ sigma@npm:2.4.0 doesn't provide graphology-types (pe610a), requested by graphology-utils
> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Fetch step
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Link step
> ➤ YN0000: └ Completed in 0s 258ms
> ➤ YN0000: Done with warnings in 0s 650ms
> {"level":"info","time":"2024-07-25T13:49:26.016716-04:00","message":"Finished yarn install for /Users/jbarnett/dev/bloodhound-enterprise/bhce/packages/javascript/js-client-library"}
> {"level":"info","time":"2024-07-25T13:49:26.01673-04:00","message":"Command `deps` completed successfully"}
> ➜  bhce git:(BED-4622) ✗ just goimports
> Running goimports, check for file drift
> find: goimports: No such file or directory
> ```

There's a successful second `go install`. My best guess is that your GOPATH isn't on your PATH, which can happen on people's macs when they use brew I think. Let's take a closer look on your system to figure it out and see if there are any mitigations we can add to st bernard

**Comment by juggernot325** [comment]
The problem was with my environment. I have Go installed via `homebrew`, which does not automatically add the installation directory to `$PATH`. `goimports` was correctly installed to `~/go/bin`, and once I added that to `$PATH` the `just goimports` command started working as expected.

This should be good to go!

**Review by juggernot325 — APPROVED** [review]

**Pull request merged**
